# Generated by Django 5.2.4 on 2025-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pickup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("base", models.CharField(max_length=10)),
                ("hour", models.IntegerField()),
                ("weekday", models.CharField(max_length=20)),
            ],
        ),
    ]
